[Interface]
Address = 10.7.0.2/24
DNS = 94.140.14.14, 94.140.15.15
PrivateKey = 8DlGWjgDXVi76fBXOyJHDsYCthqMOnutdKXNl/WOFXo=

[Peer]
PublicKey = H3GeJKmQtFIRpXKyrLR4owLXLNc7Asx1cCa0fHL6RT8=
PresharedKey = /6+t7rWQeVIRAuU0YUR1rDlSMlulEX7i1BzKSrf3i98=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 86.104.74.156:51820
PersistentKeepalive = 25
