[Interface]
PrivateKey = 2PmADYl9oeSTbc1qZ65rlXz4aL1PJXkwNTmSk5PXLHU=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

[Peer]
PublicKey = y4GZpAjA7dCdtCclYW71w0XB0mUi/QMCqGVdkZWBRh8=
PresharedKey = HwWXTD8xMjoiZc/68YFXdmAXA+okgQYxx/1oefKFTrY=
Endpoint = 185.231.206.64:65534
AllowedIPs = 0.0.0.0/0,::/0
