[Interface]
Address = 10.7.0.4/24
DNS = 94.140.14.14, 94.140.15.15
PrivateKey = GIT9DZ9wXrFCAyoqVGNdyq0iZuv4hvk45anW20MtOUM=

[Peer]
PublicKey = H3GeJKmQtFIRpXKyrLR4owLXLNc7Asx1cCa0fHL6RT8=
PresharedKey = p4yJoR/F0PB1sJjhxC2LtBzpQyyoQhSi9ZL9z7QY6Nk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 86.104.74.156:51820
PersistentKeepalive = 25
